[package]

name = "iomrascálaí"
version = "0.1.4"
authors = ["Urban Hafner <contact@urbanhafner.com>", "Thomas Poinsot <thomas.poinsot1@gmail.com>"]
homepage = "https://github.com/ujh/iomrascalai"
repository = "https://github.com/ujh/iomrascalai"

[dependencies]

getopts         = "*"
rand            = "*"
regex           = "*"
regex_macros    = "*"
rustc-serialize = "*"
time            = "*"
