log = true
play_out_aftermath = false
ruleset = "chinese"
threads = 8

[playout]

atari_check = true
ladder_check = true
last_moves_for_heuristics = 2
pattern_probability = 0.9
play_in_middle_of_eye = true

[priors]

best_move_factor = 1.0
capture_many = 30
capture_one = 15
empty = 20
neutral_plays = 10
neutral_wins = 5
patterns = 10
self_atari = 10
use_patterns = true

[time_control]

c = 0.5
fastplay20_thres = 0.8
fastplay5_thres = 0.95

[tree]

end_of_game_cutoff = 0.08
expand_after = 1
rave_equiv = 20.0
reuse_subtree = true
