gfx = true
log = true
ruleset = "chinese"

[playout]

atari_check = 1.0
ladder_check = 1.0
last_moves_for_heuristics = 2
pattern_probability = 0.9
play_in_middle_of_eye = 1.0

[priors]

best_move_factor = 1.0
capture_many = 30
capture_one = 15
empty = 20
neutral_plays = 10
neutral_wins = 5
patterns = 10
self_atari = 10

[time_control]

c = 0.456212
fastplay_threshold = 0.842075
fastplay_budget = 0.05
min_stones = 30

[tree]

expand_after = 1
rave_equiv = 20.0
score_weight = 0.0653414

[scoring]

ownership_prior = 64
ownership_cutoff = 0.858546
