log = true
play_out_aftermath = false
ruleset = "chinese"
threads = 8

[playout]

atari_check = 1.0
ladder_check = 1.0
last_moves_for_heuristics = 2
pattern_probability = 0.9
play_in_middle_of_eye = 1.0

[priors]

best_move_factor = 0.713554
capture_many = 57
capture_one = 54
empty = 41
neutral_plays = 10
neutral_wins = 5
patterns = 26
self_atari = 48

[time_control]

c = 0.5
fastplay20_thres = 0.8
fastplay5_thres = 0.95

[tree]

end_of_game_cutoff = 0.08
expand_after = 1
rave_equiv = 20.0
reuse_subtree = true
